name: Build & Test

on: [push, pull_request]

jobs:
  build_test:
    name: Build and test bitfield
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python -m pip install --upgrade pip
      - run: pip install .
      - run: pip install pytest && pytest .

